project_id = "nsyaecxzjqruqkbnaael"

[functions.delete-user]
verify_jwt = true

[functions.auto-end-events]
verify_jwt = false

[functions.extract-events]
verify_jwt = true

[functions.generate-event-description]
verify_jwt = true

[functions.extract-event-from-image]
verify_jwt = true
