// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsyaecxzjqruqkbnaael.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zeWFlY3h6anFydXFrYm5hYWVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMjQwMjgsImV4cCI6MjA3MzcwMDAyOH0.bTmmKPcStHhkJgi0SJZjz-8YEll--FfRBvZH8ObOdKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});